const countries = [
  { code: "AF", name: "Afghanistan" },
  { code: "AX", name: "Aland Islands" },
  { code: "AL", name: "Albania" },
  { code: "DZ", name: "Algeria" },
  { code: "AS", name: "American Samoa" },
  { code: "AD", name: "Andorra" },
  { code: "AO", name: "Angola" },
  { code: "AI", name: "Anguilla" },
  { code: "AQ", name: "Antarctica" },
  { code: "AG", name: "Antigua And Barbuda" },
  { code: "AR", name: "Argentina" },
  { code: "AM", name: "Armenia" },
  { code: "AW", name: "Aruba" },
  { code: "AU", name: "Australia" },
  { code: "AT", name: "Austria" },
  { code: "AZ", name: "Azerbaijan" },
  { code: "BS", name: "Bahamas" },
  { code: "BH", name: "Bahrain" },
  { code: "BD", name: "Bangladesh" },
  { code: "BB", name: "Barbados" },
  { code: "BY", name: "Belarus" },
  { code: "BE", name: "Belgium" },
  { code: "BZ", name: "Belize" },
  { code: "BJ", name: "Benin" },
  { code: "BM", name: "Bermuda" },
  { code: "BT", name: "Bhutan" },
  { code: "BO", name: "Bolivia" },
  { code: "BA", name: "Bosnia And Herzegovina" },
  { code: "BW", name: "Botswana" },
  { code: "BV", name: "Bouvet Island" },
  { code: "BR", name: "Brazil" },
  { code: "IO", name: "British Indian Ocean Territory" },
  { code: "BN", name: "Brunei Darussalam" },
  { code: "BG", name: "Bulgaria" },
  { code: "BF", name: "Burkina Faso" },
  { code: "BI", name: "Burundi" },
  { code: "KH", name: "Cambodia" },
  { code: "CM", name: "Cameroon" },
  { code: "CA", name: "Canada" },
  { code: "CV", name: "Cape Verde" },
  { code: "KY", name: "Cayman Islands" },
  { code: "CF", name: "Central African Republic" },
  { code: "TD", name: "Chad" },
  { code: "CL", name: "Chile" },
  { code: "CN", name: "China" },
  { code: "CX", name: "Christmas Island" },
  { code: "CC", name: "Cocos (Keeling) Islands" },
  { code: "CO", name: "Colombia" },
  { code: "KM", name: "Comoros" },
  { code: "CG", name: "Congo" },
  { code: "CD", name: "Congo}, Democratic Republic" },
  { code: "CK", name: "Cook Islands" },
  { code: "CR", name: "Costa Rica" },
  { code: "CI", name: "Cote D/'Ivoire" },
  { code: "HR", name: "Croatia" },
  { code: "CU", name: "Cuba" },
  { code: "CY", name: "Cyprus" },
  { code: "CZ", name: "Czech Republic" },
  { code: "DK", name: "Denmark" },
  { code: "DJ", name: "Djibouti" },
  { code: "DM", name: "Dominica" },
  { code: "DO", name: "Dominican Republic" },
  { code: "EC", name: "Ecuador" },
  { code: "EG", name: "Egypt" },
  { code: "SV", name: "El Salvador" },
  { code: "GQ", name: "Equatorial Guinea" },
  { code: "ER", name: "Eritrea" },
  { code: "EE", name: "Estonia" },
  { code: "ET", name: "Ethiopia" },
  { code: "FK", name: "Falkland Islands (Malvinas)" },
  { code: "FO", name: "Faroe Islands" },
  { code: "FJ", name: "Fiji" },
  { code: "FI", name: "Finland" },
  { code: "FR", name: "France" },
  { code: "GF", name: "French Guiana" },
  { code: "PF", name: "French Polynesia" },
  { code: "TF", name: "French Southern Territories" },
  { code: "GA", name: "Gabon" },
  { code: "GM", name: "Gambia" },
  { code: "GE", name: "Georgia" },
  { code: "DE", name: "Germany" },
  { code: "GH", name: "Ghana" },
  { code: "GI", name: "Gibraltar" },
  { code: "GR", name: "Greece" },
  { code: "GL", name: "Greenland" },
  { code: "GD", name: "Grenada" },
  { code: "GP", name: "Guadeloupe" },
  { code: "GU", name: "Guam" },
  { code: "GT", name: "Guatemala" },
  { code: "GG", name: "Guernsey" },
  { code: "GN", name: "Guinea" },
  { code: "GW", name: "Guinea-Bissau" },
  { code: "GY", name: "Guyana" },
  { code: "HT", name: "Haiti" },
  { code: "HM", name: "Heard Island & Mcdonald Islands" },
  { code: "VA", name: "Holy See (Vatican City State)" },
  { code: "HN", name: "Honduras" },
  { code: "HK", name: "Hong Kong" },
  { code: "HU", name: "Hungary" },
  { code: "IS", name: "Iceland" },
  { code: "IN", name: "India" },
  { code: "ID", name: "Indonesia" },
  { code: "IR", name: "Iran}, Islamic Republic Of" },
  { code: "IQ", name: "Iraq" },
  { code: "IE", name: "Ireland" },
  { code: "IM", name: "Isle Of Man" },
  { code: "IL", name: "Israel" },
  { code: "IT", name: "Italy" },
  { code: "JM", name: "Jamaica" },
  { code: "JP", name: "Japan" },
  { code: "JE", name: "Jersey" },
  { code: "JO", name: "Jordan" },
  { code: "KZ", name: "Kazakhstan" },
  { code: "KE", name: "Kenya" },
  { code: "KI", name: "Kiribati" },
  { code: "KR", name: "Korea" },
  { code: "KW", name: "Kuwait" },
  { code: "KG", name: "Kyrgyzstan" },
  { code: "LA", name: "Lao People/'s Democratic Republic" },
  { code: "LV", name: "Latvia" },
  { code: "LB", name: "Lebanon" },
  { code: "LS", name: "Lesotho" },
  { code: "LR", name: "Liberia" },
  { code: "LY", name: "Libyan Arab Jamahiriya" },
  { code: "LI", name: "Liechtenstein" },
  { code: "LT", name: "Lithuania" },
  { code: "LU", name: "Luxembourg" },
  { code: "MO", name: "Macao" },
  { code: "MK", name: "Macedonia" },
  { code: "MG", name: "Madagascar" },
  { code: "MW", name: "Malawi" },
  { code: "MY", name: "Malaysia" },
  { code: "MV", name: "Maldives" },
  { code: "ML", name: "Mali" },
  { code: "MT", name: "Malta" },
  { code: "MH", name: "Marshall Islands" },
  { code: "MQ", name: "Martinique" },
  { code: "MR", name: "Mauritania" },
  { code: "MU", name: "Mauritius" },
  { code: "YT", name: "Mayotte" },
  { code: "MX", name: "Mexico" },
  { code: "FM", name: "Micronesia}, Federated States Of" },
  { code: "MD", name: "Moldova" },
  { code: "MC", name: "Monaco" },
  { code: "MN", name: "Mongolia" },
  { code: "ME", name: "Montenegro" },
  { code: "MS", name: "Montserrat" },
  { code: "MA", name: "Morocco" },
  { code: "MZ", name: "Mozambique" },
  { code: "MM", name: "Myanmar" },
  { code: "NA", name: "Namibia" },
  { code: "NR", name: "Nauru" },
  { code: "NP", name: "Nepal" },
  { code: "NL", name: "Netherlands" },
  { code: "AN", name: "Netherlands Antilles" },
  { code: "NC", name: "New Caledonia" },
  { code: "NZ", name: "New Zealand" },
  { code: "NI", name: "Nicaragua" },
  { code: "NE", name: "Niger" },
  { code: "NG", name: "Nigeria" },
  { code: "NU", name: "Niue" },
  { code: "NF", name: "Norfolk Island" },
  { code: "MP", name: "Northern Mariana Islands" },
  { code: "NO", name: "Norway" },
  { code: "OM", name: "Oman" },
  { code: "PK", name: "Pakistan" },
  { code: "PW", name: "Palau" },
  { code: "PS", name: "Palestinian Territory}, Occupied" },
  { code: "PA", name: "Panama" },
  { code: "PG", name: "Papua New Guinea" },
  { code: "PY", name: "Paraguay" },
  { code: "PE", name: "Peru" },
  { code: "PH", name: "Philippines" },
  { code: "PN", name: "Pitcairn" },
  { code: "PL", name: "Poland" },
  { code: "PT", name: "Portugal" },
  { code: "PR", name: "Puerto Rico" },
  { code: "QA", name: "Qatar" },
  { code: "RE", name: "Reunion" },
  { code: "RO", name: "Romania" },
  { code: "RU", name: "Russian Federation" },
  { code: "RW", name: "Rwanda" },
  { code: "BL", name: "Saint Barthelemy" },
  { code: "SH", name: "Saint Helena" },
  { code: "KN", name: "Saint Kitts And Nevis" },
  { code: "LC", name: "Saint Lucia" },
  { code: "MF", name: "Saint Martin" },
  { code: "PM", name: "Saint Pierre And Miquelon" },
  { code: "VC", name: "Saint Vincent And Grenadines" },
  { code: "WS", name: "Samoa" },
  { code: "SM", name: "San Marino" },
  { code: "ST", name: "Sao Tome And Principe" },
  { code: "SA", name: "Saudi Arabia" },
  { code: "SN", name: "Senegal" },
  { code: "RS", name: "Serbia" },
  { code: "SC", name: "Seychelles" },
  { code: "SL", name: "Sierra Leone" },
  { code: "SG", name: "Singapore" },
  { code: "SK", name: "Slovakia" },
  { code: "SI", name: "Slovenia" },
  { code: "SB", name: "Solomon Islands" },
  { code: "SO", name: "Somalia" },
  { code: "ZA", name: "South Africa" },
  { code: "GS", name: "South Georgia And Sandwich Isl." },
  { code: "ES", name: "Spain" },
  { code: "LK", name: "Sri Lanka" },
  { code: "SD", name: "Sudan" },
  { code: "SR", name: "Suriname" },
  { code: "SJ", name: "Svalbard And Jan Mayen" },
  { code: "SZ", name: "Swaziland" },
  { code: "SE", name: "Sweden" },
  { code: "CH", name: "Switzerland" },
  { code: "SY", name: "Syrian Arab Republic" },
  { code: "TW", name: "Taiwan" },
  { code: "TJ", name: "Tajikistan" },
  { code: "TZ", name: "Tanzania" },
  { code: "TH", name: "Thailand" },
  { code: "TL", name: "Timor-Leste" },
  { code: "TG", name: "Togo" },
  { code: "TK", name: "Tokelau" },
  { code: "TO", name: "Tonga" },
  { code: "TT", name: "Trinidad And Tobago" },
  { code: "TN", name: "Tunisia" },
  { code: "TR", name: "Turkey" },
  { code: "TM", name: "Turkmenistan" },
  { code: "TC", name: "Turks And Caicos Islands" },
  { code: "TV", name: "Tuvalu" },
  { code: "UG", name: "Uganda" },
  { code: "UA", name: "Ukraine" },
  { code: "AE", name: "United Arab Emirates" },
  { code: "GB", name: "United Kingdom" },
  { code: "US", name: "United States" },
  { code: "UM", name: "United States Outlying Islands" },
  { code: "UY", name: "Uruguay" },
  { code: "UZ", name: "Uzbekistan" },
  { code: "VU", name: "Vanuatu" },
  { code: "VE", name: "Venezuela" },
  { code: "VN", name: "Vietnam" },
  { code: "VG", name: "Virgin Islands}, British" },
  { code: "VI", name: "Virgin Islands}, U.S." },
  { code: "WF", name: "Wallis And Futuna" },
  { code: "EH", name: "Western Sahara" },
  { code: "YE", name: "Yemen" },
  { code: "ZM", name: "Zambia" },
  { code: "ZW", name: "Zimbabwe" },
];
const dates = [
  { code: "01", date: 1 },
  { code: "02", date: 2 },
  { code: "03", date: 3 },
  { code: "04", date: 4 },
  { code: "05", date: 5 },
  { code: "06", date: 6 },
  { code: "07", date: 7 },
  { code: "08", date: 8 },
  { code: "09", date: 9 },
  { code: "10", date: 10 },
  { code: "11", date: 11 },
  { code: "12", date: 12 },
  { code: "13", date: 13 },
  { code: "14", date: 14 },
  { code: "15", date: 15 },
  { code: "16", date: 16 },
  { code: "17", date: 17 },
  { code: "18", date: 18 },
  { code: "19", date: 19 },
  { code: "20", date: 20 },
  { code: "21", date: 21 },
  { code: "22", date: 22 },
  { code: "23", date: 23 },
  { code: "24", date: 24 },
  { code: "25", date: 25 },
  { code: "26", date: 26 },
  { code: "27", date: 27 },
  { code: "28", date: 28 },
  { code: "29", date: 29 },
  { code: "30", date: 30 },
  { code: "31", date: 31 },
];
const months = [
  { monthNo: "01", monthName: "January" },
  { monthNo: "02", monthName: "February" },
  { monthNo: "03", monthName: "March" },
  { monthNo: "04", monthName: "April" },
  { monthNo: "05", monthName: "May" },
  { monthNo: "06", monthName: "June" },
  { monthNo: "07", monthName: "July" },
  { monthNo: "08", monthName: "August" },
  { monthNo: "09", monthName: "September" },
  { monthNo: "10", monthName: "October" },
  { monthNo: "11", monthName: "November" },
  { monthNo: "12", monthName: "December" },
];
const years = [
  { yearCode: "2006", yearNo: 2006 },
  { yearCode: "2005", yearNo: 2005 },
  { yearCode: "2004", yearNo: 2004 },
  { yearCode: "2003", yearNo: 2003 },
  { yearCode: "2002", yearNo: 2002 },
  { yearCode: "2001", yearNo: 2001 },
  { yearCode: "2000", yearNo: 2000 },
  { yearCode: "1999", yearNo: 1999 },
  { yearCode: "1998", yearNo: 1998 },
  { yearCode: "1997", yearNo: 1997 },
  { yearCode: "1996", yearNo: 1996 },
  { yearCode: "1995", yearNo: 1995 },
  { yearCode: "1994", yearNo: 1994 },
  { yearCode: "1993", yearNo: 1993 },
  { yearCode: "1992", yearNo: 1992 },
  { yearCode: "1991", yearNo: 1991 },
  { yearCode: "1990", yearNo: 1990 },
  { yearCode: "1989", yearNo: 1989 },
  { yearCode: "1988", yearNo: 1988 },
  { yearCode: "1987", yearNo: 1987 },
  { yearCode: "1986", yearNo: 1986 },
  { yearCode: "1985", yearNo: 1985 },
  { yearCode: "1984", yearNo: 1984 },
  { yearCode: "1983", yearNo: 1983 },
  { yearCode: "1982", yearNo: 1982 },
  { yearCode: "1981", yearNo: 1981 },
  { yearCode: "1980", yearNo: 1980 },
  { yearCode: "1979", yearNo: 1979 },
  { yearCode: "1978", yearNo: 1978 },
  { yearCode: "1977", yearNo: 1977 },
  { yearCode: "1976", yearNo: 1976 },
  { yearCode: "1975", yearNo: 1975 },
  { yearCode: "1974", yearNo: 1974 },
  { yearCode: "1973", yearNo: 1973 },
  { yearCode: "1972", yearNo: 1972 },
  { yearCode: "1971", yearNo: 1971 },
  { yearCode: "1970", yearNo: 1970 },
  { yearCode: "1969", yearNo: 1969 },
  { yearCode: "1968", yearNo: 1968 },
  { yearCode: "1967", yearNo: 1967 },
  { yearCode: "1966", yearNo: 1966 },
  { yearCode: "1965", yearNo: 1965 },
  { yearCode: "1964", yearNo: 1964 },
  { yearCode: "1963", yearNo: 1963 },
  { yearCode: "1962", yearNo: 1962 },
  { yearCode: "1961", yearNo: 1961 },
  { yearCode: "1960", yearNo: 1960 },
  { yearCode: "1959", yearNo: 1959 },
  { yearCode: "1958", yearNo: 1958 },
  { yearCode: "1957", yearNo: 1957 },
  { yearCode: "1956", yearNo: 1956 },
  { yearCode: "1955", yearNo: 1955 },
  { yearCode: "1954", yearNo: 1954 },
  { yearCode: "1953", yearNo: 1953 },
  { yearCode: "1952", yearNo: 1952 },
  { yearCode: "1951", yearNo: 1951 },
  { yearCode: "1950", yearNo: 1950 },
  { yearCode: "1949", yearNo: 1949 },
  { yearCode: "1948", yearNo: 1948 },
  { yearCode: "1947", yearNo: 1947 },
  { yearCode: "1946", yearNo: 1946 },
  { yearCode: "1945", yearNo: 1945 },
  { yearCode: "1944", yearNo: 1944 },
  { yearCode: "1943", yearNo: 1943 },
  { yearCode: "1942", yearNo: 1942 },
  { yearCode: "1941", yearNo: 1941 },
];

export { years, dates, months, countries };
